# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: GitHub Metrics

on:
  # Schedule daily updates
  # Note: GitHub Actions schedules run at most every 5 minutes using UTC time.
  schedule: [{cron: "0 * * * *"}] # Runs at minute 5 of every hour UTC

  # Allow manual run
  workflow_dispatch:

  # Allow running on push to main/master branch
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to commit the generated image back to the repository

    steps:
      - uses: actions/checkout@v4 # Checkout the repository

      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest # Use the latest version of the metrics action
        with:
          # Your GitHub token
          # Refer to documentation for required scopes
          token: ${{ secrets.METRICS_TOKEN }} # Use the secret

          # Basic options
          user: MaiFengYXD
          template: classic
          base: header, activity, community, repositories, metadata, completion
          config_timezone: Asia/Shanghai

          # Plugin options
          plugin_achievements: no
          plugin_achievements_display: detailed
          plugin_achievements_secrets: yes
          plugin_achievements_threshold: C
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_visibility: public
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_analysis_timeout_repositories: 7.5
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_ignored: markdown, makefile
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used, recently-used
          plugin_languages_threshold: 0%
          plugin_habits: yes
          plugin_habits_from: commits
          plugin_habits_days: 14
          plugin_habits_charts: daily, times
          plugin_habits_trim_invalid: yes
          plugin_lines: yes
          plugin_stars: yes
          plugin_stars_limit: 5
          plugin_stars_sections: featured, recently-starred
          plugin_stargazers: yes
          plugin_stargazers_limit: 5
          plugin_followup: yes
          plugin_followup_sections: issues, prs
          plugin_followup_limit: 5
          plugin_sponsorship: yes
          plugin_sponsorship_sections: display
